Repository leancloud/objc-sdk, pull requests merged in 2021-12, with the labels that each got.

#678 fix: dealloc of IM client
  AVOS/AVOS.xcodeproj/project.pbxproj
  AVOS/AVOS.xcodeproj/xcshareddata/xcschemes/LeanCloudObjcTests.xcscheme
  AVOS/LeanCloudObjcTests/LCIMClientTestCase.swift
  AVOS/LeanCloudObjcTests/LCIMMessageTestCase.swift
  AVOS/LeanCloudObjcTests/LCIMTestCase.swift
  AVOS/LeanCloudObjcTests/TestCaseDelegator.swift
  AVOS/LeanCloudObjcTests/yellowicon.png
  AVOS/Sources/Realtime/IM/Client/LCIMClient.m
  AVOS/Sources/Realtime/IM/Connection/LCRTMConnection.m
  AVOS/Sources/Realtime/IM/Connection/LCRTMConnection_Internal.h
Labels: fix

#683 refactor: message media type
  AVOS/LeanCloudObjcTests/LCIMConversationTestCase.swift
  AVOS/LeanCloudObjcTests/LCIMMessageTestCase.swift
  AVOS/Sources/Realtime/IM/Conversation/LCIMConversation.m
  AVOS/Sources/Realtime/IM/Message/LCIMMessage.h
  AVOS/Sources/Realtime/IM/Message/LCIMMessage.m
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMAudioMessage.m
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMFileMessage.m
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMImageMessage.m
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMLocationMessage.m
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMRecalledMessage.m
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMTextMessage.m
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMTypedMessage.h
  AVOS/Sources/Realtime/IM/TypedMessages/LCIMVideoMessage.m
  main.swift
Labels: refactor

#685 feat: validator for http client
  AVOS/Sources/Foundation/Request/LCPaasClient.h
  AVOS/Sources/Foundation/Request/LCPaasClient.m
Labels: feat
